# Generated by Django 4.1 on 2022-08-15 04:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0003_alter_room_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="participants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
